# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39e1dedde246fb7a6814ed8434075411999e21667e69a683b5c24cab293d40ae9343241294c382fdfa7c50c73b9d657dd3d1bfddc00a0e1f724a63de0d4640bf

test:
  secret_key_base: 0ef995d61f411bac6fba68889410cf4318c5b0f6939bff3dbc5696b29c748f1dfaf756004bb58a348f3a1b6bf669b713cb7ae9aa0875702b8537de3fd394bc82

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
